  
name: Greetings
# This line tell when should action run that is on pull request and on issue open 
on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          #This line has msg which will be displayed on creating issue 
          issue-message: "Hi👋 thanks for taking the time to create an issue on my Readme Profile!! I will get back to you soon. Your contribution means a lot to me 😊"
          #This line has msg which will be displayed on creating PR
          pr-message: "🎉Congratulations!!🎉 for making PR, I will review it soon. Your contribution means a lot to me 😊"
